<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:qfix="http://baxter-it.com/price-engine/conf/qfix"
    xmlns:c="http://baxter-it.com/config/component" xmlns:conf="http://baxter-it.com/config"
    exclude-result-prefixes="xs" version="2.0">

    <xsl:import href="baxterxsl:repo-base.xsl"/>
    <xsl:import href="baxterxsl:text-fmt.xsl"/>
    <xsl:import href="baxterxsl:conf-reference.xsl"/>

    <xsl:output method="text" encoding="UTF-8" omit-xml-declaration="yes"/>

    <xsl:param name="configurationProductId"/>
    <xsl:param name="configurationComponentId"/>
    <xsl:param name="configurationVariant"/>

    <xsl:template match="/">
        <xsl:variable name="root">
            <xsl:copy-of select="configuration-source/request"/>
            <xsl:call-template name="load-merged-repo-document">
                <xsl:with-param name="prefix" select="'qfix'"/>
            </xsl:call-template>
        </xsl:variable>
        <xsl:apply-templates select="$root/qfix:configuration"/>
    </xsl:template>

    <xsl:template match="qfix:configuration">
        <xsl:text>#################################</xsl:text>
        <xsl:call-template name="CRLF"/>
        <xsl:text># QuickFix related Parameters!!!#</xsl:text>
        <xsl:call-template name="CRLF"/>
        <xsl:text># Generated by BaxterConfig  :) #</xsl:text>
        <xsl:call-template name="CRLF"/>
        <xsl:text>#################################</xsl:text>
        <xsl:call-template name="CRLF"/>
        <xsl:call-template name="CRLF"/>
        <xsl:call-template name="render-default-section"/>
        <xsl:call-template name="CRLF"/>
        <xsl:apply-templates select="qfix:session[@id=/request/parameter[@id='session']/text()]"/>
    </xsl:template>


    <xsl:template match="qfix:default[text()='true']">
        <xsl:value-of select="@id"/>
        <xsl:text>=Y</xsl:text>
        <xsl:call-template name="CRLF"/>
    </xsl:template>

    <xsl:template match="qfix:default[text()='false']">
        <xsl:value-of select="@id"/>
        <xsl:text>=N</xsl:text>
        <xsl:call-template name="CRLF"/>
    </xsl:template>

    <xsl:template match="qfix:default">
        <xsl:value-of select="@id"/>
        <xsl:text>=</xsl:text>
        <xsl:value-of select="."/>
        <xsl:call-template name="CRLF"/>
    </xsl:template>

    <xsl:template match="qfix:defaults">
        <xsl:apply-templates select="qfix:default"/>
    </xsl:template>

    <xsl:template name="render-default-section">
        <xsl:text>[DEFAULT]</xsl:text>
        <xsl:call-template name="CRLF"/>
        <xsl:apply-templates select="qfix:defaults[@id=/request/parameter[@id='defaults']/text()]"/>
    </xsl:template>

    <xsl:template match="qfix:session">
        <xsl:text>[SESSION]</xsl:text>
        <xsl:call-template name="CRLF"/>
        <xsl:text>BeginString=</xsl:text>
        <xsl:value-of select="@beginString"/>
        <xsl:call-template name="CRLF"/>
        <xsl:text>TargetCompID=</xsl:text>
        <xsl:value-of select="@target"/>
        <xsl:call-template name="CRLF"/>
        <xsl:apply-templates select="../qfix:time[@id=current()/@time]"/>
        <xsl:text>HeartBtInt=</xsl:text>
        <xsl:value-of select="@heartbeatInterval"/>
        <xsl:call-template name="CRLF"/>
        <xsl:text>DataDictionary=</xsl:text>
        <xsl:apply-templates select="conf:reference[@id='DataDictionary']" mode="url"/>
        <xsl:call-template name="CRLF"/>
        <xsl:apply-templates select="../qfix:connection[@id=current()/@connection]"/>
    </xsl:template>

    <xsl:template match="qfix:time">
        <xsl:text>StartTime=</xsl:text>
        <xsl:value-of select="@start"/>
        <xsl:call-template name="CRLF"/>
        <xsl:text>EndTime=</xsl:text>
        <xsl:value-of select="@end"/>
        <xsl:call-template name="CRLF"/>
    </xsl:template>

    <xsl:template match="qfix:ssl">
        <xsl:text>SocketUseSSL=Y</xsl:text>
        <xsl:call-template name="CRLF"/>
        <xsl:text>SocketKeyStore=</xsl:text>
        <xsl:apply-templates select="conf:reference[@id='SocketKeyStore']" mode="url"/>
        <xsl:call-template name="CRLF"/>
        <xsl:text>SocketKeyStorePassword=</xsl:text>
        <xsl:value-of select="@password"/>
        <xsl:call-template name="CRLF"/>
    </xsl:template>

    <xsl:template match="qfix:connection">
        <xsl:text>SocketConnectPort=</xsl:text>
        <xsl:value-of select="@port"/>
        <xsl:call-template name="CRLF"/>
        <xsl:text>SocketConnectHost=</xsl:text>
        <xsl:value-of select="@host"/>
        <xsl:call-template name="CRLF"/>
        <xsl:if test="@resetOnLogon = 'true'">
            <xsl:text>ResetOnLogon=Y</xsl:text>
            <xsl:call-template name="CRLF"/>
        </xsl:if>
        <xsl:apply-templates select="qfix:ssl"/>
    </xsl:template>

</xsl:stylesheet>
