#!/bin/sh
#
# Verify the product user exists or create one
#
echo "Verifying if user ${unix.user} exists..."
if ! getent passwd ${unix.user} > /dev/null; then
    adduser -M --system --user-group ${unix.user}
fi
