#!/bin/sh
#
# Verify the product user exists or create one
#
echo "Verifying if user exists..."
if ! getent passwd ${unix.user} > /dev/null; then
    adduser ${unix.user} --quiet --system --group --no-create-home
fi
