#!/bin/sh

#
# Need to stop the service before removing
#
echo "Stopping ${unix.service} service(s)..."
service ${unix.service} stop

#
# When we remove the package we do not need the service anymore
#
echo "Unregistering ${unix.service} service..."
update-rc.d -f ${unix.service} remove
